Bundle FFI bridges to expose as packages for other platforms (#2)
* Checkpoint apple connlib

* Building on Android successfully

* ignore local .env files

* Remove ndis/virtnet from build

* Android logger and FFI are working in both directions

* Remove Cargo.lock from git

* stub tests

* Appease the build gods by requiring x25519-dalek in root

* refactor Package.swift into two packages

* remove product

* Add swift-tools boilerplate

* still trying to figure obscure git error

* does relative path work...

* extra relative

* Checkpoint making connlib an XCFramework for apple

* Checkpoint working framework build

* Fix iOS build

* lint fixes

* Fix linux/windows build errors

* Add pre-commit for linting

* Fix types

* Appease clippy

* capitalize tun name

* Finally got apple build fixed

* Add GA workflows

* Add pr-labeler, release-drafter

* Clarify build step

* Remove deprecated platforms

* Debug CI

* Explicitly add wrapper jar

* Fix Apple scheme typo

* Add destination

* Add rust to build steps

* Build rust first

* cache platform builds

* Add lipo

* Allow improper ctypes; look into later

* Fix build apple

* Don't build sim in CI

* Get scheme names to align

* Only build for nightly

* Add *some* XCode files to git

* No profile

* Pass RUSTFLAGS properly

* show llvm location

* Use /usr/local as Homebrew prefix for x86_64

* try using zig...

* Remove SDK root

* Build for Release

* Finish Apple fixes

* zip framework

* Set different debug and non-debug logging levels

Co-authored-by: Gabi <gabrielalejandro7@gmail.com>

* Address PR comments

* Cache cargo binaries

---------

Co-authored-by: Gabi <gabrielalejandro7@gmail.com>

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -11,16 +11,24 @@ env:
   CARGO_NET_GIT_FETCH_WITH_CLI: true
 
 jobs:
-  static_analysis:
+  draft-release:
+    runs-on: ubuntu-latest
+    outputs:
+      tag_name: ${{ steps.release_drafter.outputs.tag_name }}
+    steps:
+      - uses: release-drafter/release-drafter@v5
+        id: release_drafter
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+  static-analysis:
     name: Static analysis
     strategy:
       matrix:
         rust: [stable, nightly]
         runs-on:
-          - ubuntu-18.04 # Deprecated
           - ubuntu-20.04
           - ubuntu-22.04
-          - macos-10.15 # Deprecated
           - macos-11
           - macos-12
           - windows-2019
@@ -40,14 +48,153 @@ jobs:
           key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
       - name: Update toolchain
         run: rustup update --no-self-update ${{ matrix.rust }} && rustup default ${{ matrix.rust }} && rustup component add clippy
-      - name: Authenticate SSH agent
-        uses: webfactory/ssh-agent@v0.7.0
-        with:
-          ssh-private-key: |
-            ${{ secrets.VIRTNET_CLONE_KEY }}
-            ${{ secrets.NDISAPI_CLONE_KEY }}
       - name: Run cargo static analysis checks
         run: |
           cargo check
           cargo clippy -- -D clippy::all
           cargo test
+
+  build-android:
+    needs: static-analysis
+    runs-on: ubuntu-latest
+    permissions:
+      contents: read
+    strategy:
+      matrix:
+        rust: [stable]
+    steps:
+      - uses: actions/checkout@v3
+      - uses: actions/cache@v3
+        with:
+          path: |
+            ~/.cargo/bin/
+            ~/.cargo/registry/index/
+            ~/.cargo/registry/cache/
+            ~/.cargo/git/db/
+            apple/target/
+            android/target/
+            target/
+          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
+      - name: Setup toolchain
+        run: |
+          rustup update --no-self-update ${{ matrix.rust }} \
+          && rustup default ${{ matrix.rust }} \
+          && rustup component add clippy \
+          && rustup target add x86_64-linux-android arm-linux-androideabi aarch64-linux-android armv7-linux-androideabi i686-linux-android
+
+      - uses: actions/cache@v3
+        with:
+          path: |
+            ~/.gradle/caches
+            ~/.gradle/wrapper
+          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
+          restore-keys: |
+            ${{ runner.os }}-gradle-
+      - uses: actions/setup-java@v3
+        with:
+          java-version: '17'
+          distribution: 'adopt'
+      - name: Validate Gradle wrapper
+        uses: gradle/wrapper-validation-action@v1
+      - name: Assemble Release
+        uses: gradle/gradle-build-action@v2
+        with:
+          arguments: assembleRelease
+          build-root-directory: android
+      - name: Move artifact
+        run: |
+          mv ./android/lib/build/outputs/aar/lib-release.aar ./connlib-${{ needs.draft-release.outputs.tag_name }}
+      - uses: actions/upload-artifact@v3
+        with:
+          name: connlib-android
+          path: |
+            ./connlib-${{ needs.draft-release.outputs.tag_name }}
+
+  build-apple:
+    needs: static-analysis
+    runs-on: macos-latest
+    permissions:
+      contents: read
+    strategy:
+      matrix:
+        rust: [stable]
+    steps:
+      - uses: actions/checkout@v3
+      - uses: actions/cache@v3
+        with:
+          path: |
+            ~/.cargo/.crates.toml
+            ~/.cargo/.crates2.json
+            ~/.cargo/.package-cache
+            ~/.cargo/bin/
+            ~/.cargo/registry/index/
+            ~/.cargo/registry/cache/
+            ~/.cargo/git/db/
+            apple/target/
+            android/target/
+            target/
+          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
+      - name: Setup toolchain
+        run: |
+          rustup update --no-self-update ${{ matrix.rust }} \
+          && rustup default ${{ matrix.rust }} \
+          && rustup component add clippy \
+          && rustup target add aarch64-apple-ios aarch64-apple-darwin x86_64-apple-ios x86_64-apple-darwin \
+          && cargo install --force cargo-lipo
+
+      - uses: actions/cache@v3
+        with:
+          path: apple/.build
+          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
+          restore-keys: |
+            ${{ runner.os }}-spm-
+
+      - name: Build Connlib.xcframework.zip
+        env:
+          CONFIGURATION: Release
+          PROJECT_DIR: .
+        run: |
+          cd apple
+          # build-xcframework.sh calls build-rust.sh indirectly via `xcodebuild`, but it pollutes the environment
+          # to the point that it causes the `ring` build to fail for the aarch64-apple-darwin target. So, explicitly
+          # build first. See https://github.com/briansmith/ring/issues/1332
+          ./build-rust.sh
+          ./build-xcframework.sh
+          mv Connlib.xcframework.zip Connlib.xcframework.zip.checksum.txt ../
+      - uses: actions/upload-artifact@v3
+        with:
+          name: connlib-apple
+          path: |
+            ./Connlib.xcframework.zip
+            ./Connlib.xcframework.zip.checksum.txt
+
+  # Publish packages to the drafted release on merges to master so we can
+  # manually test them if needed. Then we can just publish the drafted release
+  # and we're good to go.
+  publish-draft:
+    if: startsWith(github.ref, 'refs/heads/master')
+    runs-on: ubuntu-latest
+    needs:
+      - build-android
+      - build-apple
+      - draft-release
+    steps:
+      - uses: actions/download-artifact@v3
+        with:
+          path: ./
+      # Does XCFramework support this?
+      # - name: Rename artifact file to tag
+      #   run: |
+      #     mv ./firezone*.rpm firezone_${{ needs.draft-release.outputs.tag_name }}-${{ matrix.platform }}.rpm || true
+      #     mv ./firezone*.deb firezone_${{ needs.draft-release.outputs.tag_name }}-${{ matrix.platform }}.deb || true
+      - name: Release
+        uses: softprops/action-gh-release@v1
+        with:
+          tag_name: ${{ needs.draft-release.outputs.tag_name }}
+          draft: true
+          files: |
+            Connlib.xcframework.zip
+            Connlib.xcframework.zip.checksum.txt
+
+            # We have a publish workflow that *also* builds/publishes to the GitHub Package Registry
+            connlib-${{ needs.draft-release.outputs.tag_name }}.aar
